name: HelloWorld

on: [push]

jobs:
  echo:
<<<<<<< HEAD
    runs-on: ubuntu-latest
    steps:
    - name: hello
      run: echo "Hello, Github Actions!"
=======
    runs-on: ubuntu-latest  
    steps:
    - name: hello
      run: echo "Hello, Github Actions!"
    
>>>>>>> a91706d (flask docker test)
